# Generated by Django 3.2.25 on 2025-05-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_auto_20250517_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='city',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='destination',
            name='region',
            field=models.CharField(choices=[('addis_ababa', 'Addis Ababa'), ('afar', 'Afar'), ('amhara', 'Amhara'), ('benishangul_gumuz', 'Benishangul-Gumuz'), ('diredawa', 'Dire Dawa'), ('gambela', 'Gambela'), ('harari', 'Harari'), ('oromia', 'Oromia'), ('sidama', 'Sidama'), ('somali', 'Somali'), ('south_west', 'South West'), ('southern', 'Southern'), ('tigray', 'Tigray')], max_length=1000),
        ),
    ]
